name: Pull Request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2

      - name: Installing Dependancies
        run: |
          pip install flake8
      
      - name: Running Linter flake8
        run: flake8

  unit-tests:
    needs:
      - linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Installing Dependancies
        run: |
          pip install pyspark
          pip install delta-spark
      
      - name: Running Unit Tests
        run: |
          python -m unittest tests/test_*.py