name: release
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets['DATABRICKS_HOST_PRD'] }}
      DATABRICKS_TOKEN: ${{ secrets['DATABRICKS_TOKEN_PRD'] }}
      ENV: prod
      INTEGRATION_TEST: "NO"
      REPO_PATH: "/Repos/shivam.panicker@databricks.com/cicd_with_databricks"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Installing Dependancies
        run: |
          pip install pyspark
          pip install delta-spark
      
      - name: Running Unit Tests
        run: |
          python -m unittest tests/bronze/test_*.py