name: release
on: push

jobs:
  run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: ./src/main/tests/test_all.py
         databricks-host: ${{secrets.DATABRICKS_HOST_PRD}}
         databricks-token: ${{secrets.DATABRICKS_TOKEN_PRD}}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "i3.xlarge"
           }